-- DROP SCHEMA chat;

CREATE SCHEMA chat AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA chat IS 'standard public schema';

-- DROP SEQUENCE chat.chat_id_seq;

CREATE SEQUENCE chat.chat_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE chat.user_id_seq;

CREATE SEQUENCE chat.user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE chat.user_photos_id_seq;

CREATE SEQUENCE chat.user_photos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- chat.chat definition

-- Drop table

-- DROP TABLE chat.chat;

CREATE TABLE chat.chat (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(45) NOT NULL,
	url text NOT NULL,
	"type" varchar(25) NOT NULL,
	CONSTRAINT chat_pk PRIMARY KEY (id),
	CONSTRAINT chat_unique UNIQUE (url)
);


-- chat."user" definition

-- Drop table

-- DROP TABLE chat."user";

CREATE TABLE chat."user" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(45) NOT NULL,
	username varchar(45) NOT NULL,
	password_hash text NOT NULL,
	email varchar(35) NOT NULL,
	phone_number varchar(25) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted bool NULL,
	delete_reason varchar(128) NULL,
	restricted bool NULL,
	restrict_reason varchar(128) NULL,
	"role" varchar(25) DEFAULT 'default'::character varying NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_unique UNIQUE (username),
	CONSTRAINT user_unique_1 UNIQUE (email),
	CONSTRAINT user_unique_2 UNIQUE (phone_number)
);