-- DROP SCHEMA chat;

CREATE SCHEMA chat AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA chat IS 'standard public schema';

-- DROP SEQUENCE chat.chat_id_seq;

CREATE SEQUENCE chat.chat_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE chat.user_id_seq;

CREATE SEQUENCE chat.user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE chat.user_photos_id_seq;

CREATE SEQUENCE chat.user_photos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- chat.chat definition

-- Drop table

-- DROP TABLE chat.chat;

CREATE TABLE chat.chat (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(45) NOT NULL,
	url text NOT NULL,
	"type" varchar(25) NOT NULL,
	CONSTRAINT chat_pk PRIMARY KEY (id),
	CONSTRAINT chat_unique UNIQUE (url)
);


-- chat."user" definition

-- Drop table

-- DROP TABLE chat."user";

CREATE TABLE chat."user" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(45) NOT NULL,
	username varchar(45) NOT NULL,
	password_hash text NOT NULL,
	email varchar(35) NOT NULL,
	phone_number varchar(25) NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	deleted bool NULL,
	delete_reason varchar(128) NULL,
	restricted bool NULL,
	restrict_reason varchar(128) NULL,
	"role" varchar(25) DEFAULT 'default'::character varying NOT NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_unique UNIQUE (username),
	CONSTRAINT user_unique_1 UNIQUE (email),
	CONSTRAINT user_unique_2 UNIQUE (phone_number)
);


-- chat.chats_members definition

-- Drop table

-- DROP TABLE chat.chats_members;

CREATE TABLE chat.chats_members (
	chat_id int4 NOT NULL,
	user_id int4 NOT NULL,
	"role" varchar(25) DEFAULT 'default'::character varying NOT NULL,
	deleted bool NULL,
	delete_reason varchar(128) NULL,
	restricted bool NULL,
	retstrict_reason varchar(128) NULL,
	CONSTRAINT chats_members_pk PRIMARY KEY (chat_id, user_id),
	CONSTRAINT chats_members_chat_fk FOREIGN KEY (chat_id) REFERENCES chat.chat(id),
	CONSTRAINT chats_members_user_fk FOREIGN KEY (user_id) REFERENCES chat."user"(id)
);
CREATE INDEX chats_members_user_id_idx ON chat.chats_members USING btree (user_id);


-- chat.contacts definition

-- Drop table

-- DROP TABLE chat.contacts;

CREATE TABLE chat.contacts (
	id int4 NOT NULL,
	owner_id int4 NOT NULL,
	phone_number varchar(25) NULL,
	email varchar(35) NOT NULL,
	first_name varchar(128) NOT NULL,
	last_name varchar(128) NULL,
	user_id int4 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT contacts_pk PRIMARY KEY (id),
	CONSTRAINT contacts_unique UNIQUE (owner_id),
	CONSTRAINT contacts_user_fk FOREIGN KEY (owner_id) REFERENCES chat."user"(id),
	CONSTRAINT contacts_user_fk_1 FOREIGN KEY (user_id) REFERENCES chat."user"(id)
);
CREATE INDEX contacts_user_id_idx ON chat.contacts USING btree (user_id);


-- chat.messages definition

-- Drop table

-- DROP TABLE chat.messages;

CREATE TABLE chat.messages (
	id int4 NOT NULL,
	chat_id int4 NOT NULL,
	sender_id int4 NOT NULL,
	message text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	edited_at timestamp NULL,
	CONSTRAINT messages_pk PRIMARY KEY (id),
	CONSTRAINT messages_chat_fk FOREIGN KEY (chat_id) REFERENCES chat.chat(id),
	CONSTRAINT messages_user_fk FOREIGN KEY (sender_id) REFERENCES chat."user"(id)
);
CREATE INDEX messages_chat_id_idx ON chat.messages USING btree (chat_id, created_at);
CREATE INDEX messages_sender_id_idx ON chat.messages USING btree (sender_id);


-- chat.sessions definition

-- Drop table

-- DROP TABLE chat.sessions;

CREATE TABLE chat.sessions (
	id uuid NOT NULL,
	user_id int4 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expired_at timestamp NOT NULL,
	last_seen_at timestamp NOT NULL,
	ip_address inet NOT NULL,
	user_agent text NOT NULL,
	CONSTRAINT sessions_pk PRIMARY KEY (id),
	CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES chat."user"(id)
);
CREATE INDEX sessions_expired_at_idx ON chat.sessions USING btree (expired_at);
CREATE INDEX sessions_user_id_idx ON chat.sessions USING btree (user_id);


-- chat.user_profile_photos definition

-- Drop table

-- DROP TABLE chat.user_profile_photos;

CREATE TABLE chat.user_profile_photos (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	url text NOT NULL,
	is_main bool DEFAULT true NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	user_id int4 NOT NULL,
	CONSTRAINT user_photos_pk PRIMARY KEY (id),
	CONSTRAINT user_photos_unique UNIQUE (url),
	CONSTRAINT user_photos_unique_1 UNIQUE (is_main),
	CONSTRAINT user_photos_user_fk FOREIGN KEY (user_id) REFERENCES chat."user"(id) ON DELETE CASCADE
);


-- chat.additional definition

-- Drop table

-- DROP TABLE chat.additional;

CREATE TABLE chat.additional (
	id int4 NOT NULL,
	file_type varchar(25) NOT NULL,
	file_url text NOT NULL,
	message_id int4 NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT additional_pk PRIMARY KEY (id),
	CONSTRAINT additional_unique UNIQUE (file_type),
	CONSTRAINT additional_unique_1 UNIQUE (file_url),
	CONSTRAINT additional_messages_fk FOREIGN KEY (message_id) REFERENCES chat.messages(id)
);
CREATE INDEX additional_message_id_idx ON chat.additional USING btree (message_id);